### ISSUE TITLE
Ensure that Use Cases are standardized

### ISSUE THREAD

**Issue by Eugenetanwl3881** [AY2223S1-CS2103T-W16-2/tp#130]
Run through use cases and ensure that the following are standardized:
1) Precondition/Postcondition (if any)
2) Add Use Cases End at each UC
3) The formatting of the sections/ subsections

Ensure that use cases are concrete/acceptable as well eventually and everyone agrees

**Comment by Ferusel** [comment]
Closed by #278 
Closed by #295
