### ISSUE TITLE
As a purchasing manager, I can search for items by tags

### ISSUE THREAD

**Issue by Eugenetanwl3881** [AY2223S1-CS2103T-W16-2/tp#18]
so that I can view all items that have the same tag.

**Comment by Ferusel** [comment]
NOTE: Moved to v1.3 iteration.

**Comment by Ferusel** [comment]
This is a new command.
Users will be able to search for tags and view the items with the tags.

It requires the inventory item model and the tag model to be implemented first.

Command format: tag find TAG_NAME

**Comment by Ferusel** [comment]
Closed by #302
