### ISSUE TITLE
Bug found: renameTag command does not show renamed tag on the item when executed

### ISSUE THREAD

**Issue by Eugenetanwl3881** [AY2223S1-CS2103T-W16-2/tp#240]
When a tag is renamed, the new name of the tag is not shown on the UI.
Will need to fix this bug in renameTagCommand.

**Comment by yixiann** [comment]
Fixed

<img width="731" alt="image" src="https://user-images.githubusercontent.com/78332456/197323650-c8d094fe-5a04-4a62-81a5-b23579cd98de.png">
