### ISSUE TITLE
Still using id/ flag in tags (DG)

### ISSUE THREAD

**Issue by Eugenetanwl3881** [AY2223S1-CS2103T-W16-2/tp#262]
Should standardise commands and remove the need for id/ flags since not used in items command.

Reminder to 

- Update UG (Commands) and DG (Diagrams) when closing this issue as well

**Comment by yixiann** [comment]
The UG and commands have been resolved. Left with the DG

**Comment by Ferusel** [comment]
Issues in DG has been closed by #295
