### ISSUE TITLE
[PE-D][Tester D] Negative final quantity string could be improved

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-2/tp#382]
> (Final Quantity) The item quantity should not be negative.

This could be written less confusingly ig?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: parnikkapore/ped#2

**Comment by yixiann** [comment]
We cannot fix this in this current implementation. Will fix in the future.
