### ISSUE TITLE
[PE-D][Tester C] listtag does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-2/tp#402]
nothing is output when listtag in input.
![image.png](https://raw.githubusercontent.com/hoang227/ped/main/files/211041c0-494b-404c-a750-b67c55aa5999.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: hoang227/ped#3

**Comment by bryanljx** [comment]
Should have been resolved in #434. To verify.
