### ISSUE TITLE
[PE-D][Tester E] Tag item not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W16-2/tp#407]
I tried to tag the item with a tag named "hlmilk", and it said it had already been tagged but the tag is not showing:

![image.png](https://raw.githubusercontent.com/tanhl2000/ped/main/files/68977219-2846-476e-86dc-7c0a4595bbc6.png)

Might be an issue with the tag command.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tanhl2000/ped#5

**Comment by bryanljx** [comment]
Should have been fixed in #434. To verify.
