### ISSUE TITLE
[PE-D][Tester A] listtag not working as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-2/tp#411]
![image.png](https://raw.githubusercontent.com/LJXSean/ped/main/files/1200b0a3-74ef-40fb-8b7f-509ced2fa619.png)

error thrown from command line and no appropriate error message can be seen from within the app.
Reproduce by executing newtag with valid input -> listtag no longer works after this.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: LJXSean/ped#6

**Comment by bryanljx** [comment]
Should be fixed in #434. To verify.
