### ISSUE TITLE
[PE-D][Tester C] something is wrong with the tag "vegetables"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-2/tp#412]
everything works fine until i add the new tag "vegetables". The output screen just become unresponsive and when an item is tagged with "vegetables" it also stops working. view command no longer work and when i tried to untag "vegetables from the item, the item just disappear from the screen.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: hoang227/ped#4

**Comment by bryanljx** [comment]
Should be fixed in #434. To verify.
