### ISSUE TITLE
[PE-D][Tester A] rename tag not working as expected

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W16-2/tp#415]
![image.png](https://raw.githubusercontent.com/LJXSean/ped/main/files/eb2e17df-6638-4d36-a071-181bd7297f4c.png)

does not work as expected

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: LJXSean/ped#7

**Comment by bryanljx** [comment]
Pending PR #436
