### ISSUE TITLE
Update UG

### ISSUE THREAD

**Issue by Ferusel** [AY2223S1-CS2103T-W16-2/tp#45]
- [x] Move draft UG into User Guide page
- [x] (Each person) Push the individual sections of the UG to the main repository, issues for each person:
    - [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/47
    - [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/48
    - [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/49
    - [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/50
    - [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/51

**Comment by RichDom2185** [comment]
Closing as completed.
