### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by Ferusel** [AY2223S1-CS2103T-W16-2/tp#46]
To add to the DG:
- [ ] Target User Profile
- [ ] Value Proposition
- [ ] User stories
- [ ] Use Cases
- [ ] NFR
- [ ] Glossary

Individual
- [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/52
- [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/53
- [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/54
- [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/55
- [x] https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/56

**Comment by RichDom2185** [comment]
Closing this issue for now. Will create other issues to build on this for a future milestone.
