### ISSUE TITLE
Update Site-Wide Settings

### ISSUE THREAD

**Issue by Ferusel** [AY2223S1-CS2103T-W16-2/tp#74]
https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/project.html#2-update-project-website-aboutus-readme

![image](https://user-images.githubusercontent.com/53888954/193066433-3af61c8c-ea1a-46a6-ac52-1c8f64c5259e.png)

**Comment by RichDom2185** [comment]
This is a typo. Should be `_config.yml`
